### ISSUE TITLE
R1233zd simulation hangs

### ISSUE THREAD

**Issue by fedetft** [modelica-3rdparty/ExternalMedia#61]
Hello,
I tried simulating R1233zd with ExternalMedia v4-dev, however, simulation hangs indefinitely without using the CPU both with Dymola 2022 and OpenModelica 1.18.1 on Linux (didn't try with Windows).
The problem seems specific to R1233zd, as the same model with R134A works fine.
I also tried compiling the same CoolProp version used by v4-dev and calling it directly from C++, e.g.
```
    printf("%f\n",PropsSI("T", "P", 1.5e5, "H", 2e5, "R1233zd(E)"));
    printf("%f\n",PropsSI("D", "P", 1.5e5, "T", 300, "R1233zd(E)"));
```
and it works fine, so the issue seems related to ExternalMedia itself.
I'm attaching the example models, a minimum working example with R134A and a non working example with R1233zd
[fede.tar.gz](https://github.com/modelica-3rdparty/ExternalMedia/files/8591080/fede.tar.gz)
.

**Comment by casella** [comment]
@jowr, could you please have a look? It looks like a problem in coolpropsolver.cpp. Thanks!

**Comment by casella** [comment]
@fedetft found the error with gdb, basically error handling is currently broken with dynamically linked libraries. We have a plan to fix this in the next one-two weeks.

**Comment by fedetftpolimi** [comment]
Yes, the simulation would hang here
https://github.com/modelica-3rdparty/ExternalMedia/blob/v4-dev/Projects/Sources/errorhandling.cpp#L37
but since Dymola does not redirect stdout the printf did not appear in the log, and since stdin is not redirected as well there appears to be no way to type enter to make the `getchar()` return.

The error that caused the call to `errorMessage` that in turn caused the hang was ultimately fixed by defining the medium as `substanceNames = {"R1233zd(E)|calc_transport=0"}` because some properties for that fluid are not defined in CoolProp
